packages:
  - 'packages/*'
  - 'web'
  - 'apps/api-gateway'
  - 'apps/api-gateway-e2e'
  - 'apps/web'
  - 'apps/web-e2e'
  - 'apps/trend-service'
  - 'apps/analysis-service'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  less: false
  nx: true
  sharp: true
  unrs-resolver: false
