packages:
  - 'packages/*'
  - 'web'
  - 'apps/api-gateway'
  - 'apps/api-gateway-e2e'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  less: false
  nx: true
  sharp: true
  unrs-resolver: false
